export const toolkitObj = [
  {
    category: 'language',
    img: '',
    title: 'JavaScript',
    projects: 0,
    level: 80,
  },
  {
    category: 'bundler',
    img: '',
    title: 'Webpack',
    projects: 0,
    level: 50,
  },
  {
    category: 'db',
    img: '',
    title: 'MongoDB',
    projects: 0,
    level: 50,
  },
  {
    category: 'db',
    img: '',
    title: 'MySQL',
    projects: 0,
    level: 30,
  },
  {
    category: 'db',
    img: '',
    title: 'PostgreSQL',
    projects: 0,
    level: 30,
  },
  {
    category: 'css-preprocessor',
    img: '',
    title: 'SASS',
    projects: 0,
    level: 80,
  },
  {
    category: 'css-preprocessor',
    img: '',
    title: 'LESS',
    projects: 0,
    level: 70,
  },
  {
    category: 'css-in-js',
    img: '',
    title: 'Styled-components',
    projects: 0,
    level: 80,
  },
  {
    category: 'css-in-js',
    img: '',
    title: 'Emotion',
    projects: 0,
    level: 70,
  },
  {
    category: 'chart-lib',
    img: '',
    title: 'Recharts',
    projects: 0,
    level: 80,
  },
  {
    category: 'ui-lib',
    img: '',
    title: 'React-bootstrap',
    projects: 0,
    level: 80,
  },
  {
    category: 'framework',
    img: '',
    title: 'Vue.js',
    projects: 0,
    level: 60,
  },
  {
    category: 'framework',
    img: '',
    title: 'Angular',
    projects: 0,
    level: 30,
  },
  {
    category: 'framework',
    img: '',
    title: 'ReactJS',
    projects: 0,
    level: 90,
  },
  {
    category: 'framework',
    img: '',
    title: 'Svelte',
    projects: 0,
    level: 60,
  },
  {
    category: 'other',
    img: '',
    title: 'Apollo',
    projects: 0,
    level: 20,
  },
  {
    category: 'other',
    img: '',
    title: 'React-router',
    projects: 0,
    level: 90,
  },
  {
    category: 'other',
    img: '',
    title: 'React-transition-group',
    projects: 0,
    level: 80,
  },
  {
    category: 'other',
    img: '',
    title: 'MomentJS',
    projects: 0,
    level: 70,
  },
  {
    category: 'other',
    img: '',
    title: 'React-i18n',
    projects: 0,
    level: 80,
  },
  {
    category: 'other',
    img: '',
    title: 'Reselect',
    projects: 0,
    level: 30,
  },
  {
    category: 'other',
    img: '',
    title: 'VisJS',
    projects: 0,
    level: 50,
  },
  {
    category: 'other',
    img: '',
    title: 'Express',
    projects: 0,
    level: 30,
  },
  {
    category: 'compiler',
    img: '',
    title: 'TypeScript',
    projects: 0,
    level: 70,
  },
  {
    category: 'compiler',
    img: '',
    title: 'Babel',
    projects: 0,
    level: 40,
  },
  {
    category: 'state-management',
    img: '',
    title: 'Redux-Saga',
    projects: 0,
    level: 90,
  },
  {
    category: 'state-management',
    img: '',
    title: 'Redux-Thunk',
    projects: 0,
    level: 70,
  },
  {
    category: 'state-management',
    img: '',
    title: 'MobX',
    projects: 0,
    level: 30,
  },
  {
    category: 'testing',
    img: '',
    title: 'Jest',
    projects: 0,
    level: 60,
  },
  {
    category: 'testing',
    img: '',
    title: 'React-testing-library',
    projects: 0,
    level: 80,
  },
  {
    category: 'testing',
    img: '',
    title: 'Enzyme',
    projects: 0,
    level: 60,
  },
  {
    category: 'testing',
    img: '',
    title: 'Cypress',
    projects: 0,
    level: 70,
  },
  {
    category: 'query-languages',
    img: '',
    title: 'GraphQL',
    projects: 0,
    level: 60,
  },
  {
    category: 'other',
    img: '',
    title: 'Hasura',
    projects: 0,
    level: 40,
  },
  {
    category: 'other',
    img: '',
    title: 'Axios',
    projects: 0,
    level: 90,
  },
  {
    category: 'other',
    img: '',
    title: 'MirageJS',
    projects: 0,
    level: 70,
  },
  {
    category: 'formatters-and-linters',
    img: '',
    title: 'ESLint',
    projects: 0,
    level: 80,
  },
  {
    category: 'formatters-and-linters',
    img: '',
    title: 'Prettier',
    projects: 0,
    level: 70,
  },
  {
    category: 'runtimes',
    img: '',
    title: 'Node.js',
    projects: 0,
    level: 50,
  },
  {
    category: 'package-managers',
    img: '',
    title: 'npm',
    projects: 0,
    level: 70,
  },
  {
    category: 'package-managers',
    img: '',
    title: 'yarn',
    projects: 0,
    level: 70,
  },
  {
    category: 'ssg-and-ssr',
    img: '',
    title: 'Gatsby',
    projects: 0,
    level: 60,
  },
  {
    category: 'ssg-and-ssr',
    img: '',
    title: 'Next.js',
    projects: 0,
    level: 75,
  },
  {
    category: 'ssg-and-ssr',
    img: '',
    title: 'Nuxt.js',
    projects: 0,
    level: 20,
  },
  {
    category: 'cms',
    img: '',
    title: 'Ghost',
    projects: 0,
    level: 60,
  },
  {
    category: 'cms',
    img: '',
    title: 'Contentful',
    projects: 0,
    level: 90,
  },
  {
    category: 'cms',
    img: '',
    title: 'October',
    projects: 0,
    level: 80,
  },
  {
    category: 'version-control',
    img: '',
    title: 'GIT',
    projects: 0,
    level: 80,
  },
  {
    category: 'version-control',
    img: '',
    title: 'GitHub',
    projects: 0,
    level: 90,
  },
  {
    category: 'version-control',
    img: '',
    title: 'GitLab',
    projects: 0,
    level: 70,
  },
  {
    category: 'version-control',
    img: '',
    title: 'Bitbucket',
    projects: 0,
    level: 70,
  },
  {
    category: 'task-runners',
    img: '',
    title: 'Gulp',
    projects: 0,
    level: 70,
  },
  {
    category: 'paas',
    img: '',
    title: 'Netlify',
    projects: 0,
    level: 60,
  },
  {
    category: 'paas',
    img: '',
    title: 'Heroku',
    projects: 0,
    level: 50,
  },
  {
    category: 'paas',
    img: '',
    title: 'Vercel',
    projects: 0,
    level: 70,
  },
]